tasks:
- install:
    extra_packages: [python3-rados]
- exec:
    all:
      - 'sudo sed -i -e "1s,^\(#!/usr/bin.*python\)[0-9]*$,\13," /usr/bin/ceph'
- ceph:
    log-whitelist:
    - wrongly marked me down
- workunit:
    env:
      PYTHON: python3
    clients:
      client.0:
        - rados/test_python.sh
